# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/sf/Desktop/emma/an2/sem2/soc/lab3/project/project/Nexys4DDR_Master.xdc

# Block Designs: bd/figura3_3/figura3_3.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==figura3_3 || ORIG_REF_NAME==figura3_3} -quiet] -quiet

# IP: bd/figura3_3/ip/figura3_3_divizor_de_ceas_0_0/figura3_3_divizor_de_ceas_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==figura3_3_divizor_de_ceas_0_0 || ORIG_REF_NAME==figura3_3_divizor_de_ceas_0_0} -quiet] -quiet

# IP: bd/figura3_3/ip/figura3_3_bin2bcd_0_0/figura3_3_bin2bcd_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==figura3_3_bin2bcd_0_0 || ORIG_REF_NAME==figura3_3_bin2bcd_0_0} -quiet] -quiet

# IP: bd/figura3_3/ip/figura3_3_bin2bcd_1_0/figura3_3_bin2bcd_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==figura3_3_bin2bcd_1_0 || ORIG_REF_NAME==figura3_3_bin2bcd_1_0} -quiet] -quiet

# IP: bd/figura3_3/ip/figura3_3_afisare_7seg_0_0/figura3_3_afisare_7seg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==figura3_3_afisare_7seg_0_0 || ORIG_REF_NAME==figura3_3_afisare_7seg_0_0} -quiet] -quiet

# IP: bd/figura3_3/ip/figura3_3_binary_counter_0_0/figura3_3_binary_counter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==figura3_3_binary_counter_0_0 || ORIG_REF_NAME==figura3_3_binary_counter_0_0} -quiet] -quiet

# IP: bd/figura3_3/ip/figura3_3_binary_counter_1_0/figura3_3_binary_counter_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==figura3_3_binary_counter_1_0 || ORIG_REF_NAME==figura3_3_binary_counter_1_0} -quiet] -quiet

# XDC: c:/Users/sf/Desktop/emma/an2/sem2/soc/lab3/project/project/project.gen/sources_1/bd/figura3_3/figura3_3_ooc.xdc
